name: environment.ymal
channels:
  - conda-forge
dependencies:
  - face_recognition==1.3.0
  - keras==2.10.0
  - numpy==1.23.3
  - pip=22.1.2
  - streamlit==1.13.0
  - pip:
      - opencv_python_headless==4.6.0.66
      - scikit_learn==1.1.2
